### ISSUE TITLE
Slot on hold-status if accounting service is down

### ISSUE THREAD

**Issue by kiran-anand14** [kiran-anand14/admgr#13]
Scenario:
 - Start accounting Service
 - Start admgr
 - Open some slots
 - Kill accounting service
 - Reserve some open slot

Expected
 - 500 Internal Server Error should be reported to Reserve Slot API
 - And slot that was put on hold should be returned back to open state

Observation
 - 424 being returned in response to Reserve Slot API
 - Slot that was being reserved remains in hold state
 - Transaction table is having entry for slot that user was trying to book

**Comment by parvez0** [comment]
Resolved https://github.com/kiran-anand14/admgr/pull/16/files

**Comment by kiran-anand14** [comment]
Fixed.
