### ISSUE TITLE
In continuation to Issue #13, Status of slot changes to booked

### ISSUE THREAD

**Issue by kiran-anand14** [kiran-anand14/admgr#14]
Scenario:
 - Run scenario as mentioned in Issue #13 
 - Kill admgr service
 - Start admgr
 - Start accounting

Expected
 - Status of the slot that was put on hold should be moved to open because accounting service hadn't charged any payment for this slot in scenario mentioned in Issue #13
 
Observed:
 - Status of the slot changed to booked. If order of starting mentioned above is changed (i.e. first accounting is started and then admgr is started), then slot moves to open state.
 - Transaction table is having entry for slot that user was trying to book

Test these scenarios thoroughly.

**Comment by parvez0** [comment]
There was an issue with transaction ID, mysql was assigning the same id to all transactions I have fixed it and made the transactionId field unique https://github.com/kiran-anand14/admgr/pull/16/files

**Comment by parvez0** [comment]
<img width="935" alt="Screenshot 2023-06-03 at 6 17 42 PM" src="https://github.com/kiran-anand14/admgr/assets/30386228/20e9de77-1471-4795-8953-705e59a9824b">
<img width="1512" alt="Screenshot 2023-06-03 at 6 17 57 PM" src="https://github.com/kiran-anand14/admgr/assets/30386228/31c4c929-ac87-4ec4-98e7-cce43907a947">

**Comment by kiran-anand14** [comment]
Fixed.
