### ISSUE TITLE
status API towards accounting should use GET, not POST

### ISSUE THREAD

**Issue by kiran-anand14** [kiran-anand14/admgr#15]

**Comment by parvez0** [comment]
If you remember the discussion we had on this we had to ask for transaction status for multiple transaction id's which was not possible to do on GET request to you suggested to move this POST

**Comment by kiran-anand14** [comment]
Please help me recall - do you mean that if we use GET with Status, then response body is not allowed? I mean what is stopping to issue GET with multiple transactions in payload?
