### ISSUE TITLE
How have you tested a scenario where /debit API is rejected by accounting service because of insufficient funds?

### ISSUE THREAD

**Issue by kiran-anand14** [kiran-anand14/admgr#19]

**Comment by parvez0** [comment]
That should be the process of accounting service I am just checking if I am getting 200 from accounting service otherwise skipping initialisation

**Comment by kiran-anand14** [comment]
That is what I am asking have you tested if accounting service sends response other than 200 OK?

**Comment by kiran-anand14** [comment]
Done.
