### ISSUE TITLE
Minor changes needed in the code organisation

### ISSUE THREAD

**Issue by kiran-anand14** [kiran-anand14/admgr#5]
Core is containing accounting service. It needs a bit of reorganisation.

Think of it like this:
MySQL DB and Accounting Services are external services. So, Account Service code should be initialised and organised like MySQL DB. Like you have storage folder, at similar level you should have accounting folder and it should have all the things which are needed for accounting, like you have it for MySQL specific code in storage folder.

Like DB connection is initiated and waited, similarly accounting service checks on status API provided by it to ensure it is up or not.

**Comment by parvez-ib** [comment]
https://github.com/kiran-anand14/admgr/pull/8

**Comment by kiran-anand14** [comment]
Fixed.
