### ISSUE TITLE
Delete API should return 403 if any of the slots is booked or on-hold

### ISSUE THREAD

**Issue by kiran-anand14** [kiran-anand14/admgr#6]
Delete API should return 403 if even one of the slots from the list of slots to be deleted is either booked or in on-hold state.

**Comment by parvez0** [comment]
The code assumes that it will only delete records with the "open" status and rejects the request if no records with the "open" status are found. It does not delete records with the "on-hold" or "booked" status.

**Comment by kiran-anand14** [comment]
But, how will admin come to know that from a range it had given for deletion, some of the records which are in booked or on-hold state are not deleted? On receiving 200 OK, Admin will assume that deletion is successful for the complete range.

Or what we can do is to return the records with 200 OK, if some of the records were not deleted because they were either in booked state or on-hold state.

**Comment by parvez0** [comment]
https://github.com/kiran-anand14/admgr/pull/12

**Comment by kiran-anand14** [comment]
Fixed.
