### ISSUE TITLE
Creation of Slots in the past date should not be allowed

### ISSUE THREAD

**Issue by kiran-anand14** [kiran-anand14/admgr#7]
While posting adslots, if any of the date in the range lies in the past, then it should return 403 Forbidden. As you can understand, admin would not open slots for the dates that have already passed.

**Comment by parvez0** [comment]
This is already handled can you tell me a case where it failed 
<img width="1082" alt="Screenshot 2023-05-30 at 6 29 16 AM" src="https://github.com/kiran-anand14/admgr/assets/30386228/ee718d1a-ffbd-4f4f-8d8a-ae4005eebfe9">

**Comment by kiran-anand14** [comment]
Somehow I am also not able to reproduce this issue. So, closing it.
